apiVersion: batch/v1
kind: CronJob
metadata:
  name: iamdreamingof-generator
  namespace: iamdreamingof
spec:
  schedule: "15 0 * * *" # Runs once a day at 00:15
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: task
              image: registry.digitalocean.com/tmhhn/iamdreamingof-generator:latest
              imagePullPolicy: Always
              env:
                - name: CDN_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: iamdreamingof-secrets
                      key: CDN_ACCESS_KEY_ID
                - name: CDN_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: iamdreamingof-secrets
                      key: CDN_SECRET_ACCESS_KEY
                - name: AI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: iamdreamingof-secrets
                      key: AI_API_KEY