name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag iamdreamingof-generator:"$GITHUB_SHA"
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Log in to DO Container Registry
      run: doctl registry login --expiry-seconds 600
    - name: Tag image
      run: docker tag iamdreamingof-generator:"$GITHUB_SHA" registry.digitalocean.com/tmhhn/iamdreamingof-generator:"$GITHUB_SHA"
    - name: Push image to DO Container Registry
      run: docker push registry.digitalocean.com/tmhhn/iamdreamingof-generator:"$GITHUB_SHA"
    - name: Tag image as latest
      run: docker tag iamdreamingof-generator:"$GITHUB_SHA" registry.digitalocean.com/tmhhn/iamdreamingof-generator:latest
    - name: Push image to DO Container Registry
      run: docker push registry.digitalocean.com/tmhhn/iamdreamingof-generator:latest